[build]
    functions = "functions"

[[headers]]
  for = "/*"
    [headers.values]
    cache-control = "max-age=900,must-revalidate"
    x-frame-options = "SAMEORIGIN"
    x-xss-protection = "1; mode=block"
    x-content-type-options = "nosniff"