backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads"
public_folder: "static/images/uploads"
collections:
  - label: "Globals"
    name: "globals"
    files:
      - label: "Config"
        name: "config"
        delete: false
        file: "src/_data/config.json"
        fields:
          - { label: "Site Name", name: "name", widget: "string" }
          - { label: "Site Url", name: "url", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - {
              label: "Language Code",
              name: "lang",
              widget: "string",
              default: "en",
            }
          - {
              label: "Author Name",
              name: "authorName",
              widget: "string",
              required: false,
            }
          - {
              label: "Author Twitter Handle",
              name: "authorHandle",
              widget: "string",
              required: false,
            }
          - {
              label: "Max posts per page",
              name: "maxPostsPerPage",
              widget: "number",
            }
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - {
                  label: "Is url to external site?",
                  name: "external",
                  widget: "boolean",
                  required: false,
                }
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "featured_image",
          widget: "image",
          required: false,
        }
      - {
          label: "Featured Image Caption",
          name: "featured_image_caption",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        search_fields: ["name"]
        value_field: name
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["name"]
        value_field: name
      - label: "Related Post"
        name: "related_post"
        widget: "object"
        summary: "{{fields.post.title}}"
        required: false
        fields:
          - label: "Post"
            name: "post"
            widget: "relation"
            collection: "posts"
            search_fields: ["title"]
            value_field: "{{slug}}"
            display_fields: ["title"]
          - {
              label: "Accompanying Highlight Text",
              name: "highlight",
              widget: "string",
            }
  - name: "categories" # Used in routes, e.g., /admin/collections/blog
    label: "Categories" # Used in the UI
    identifier_field: name
    folder: "src/categories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields foreach document, usually in front matter
      - { label: "Title", name: "name", widget: "string" }
  - name: "authors" # Used in routes, e.g., /admin/collections/blog
    label: "Authors" # Used in the UI
    folder: "src/authors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Is WPT Staff",
          name: "is_staff",
          widget: "boolean",
          hint: "Checking the box will include the author as a Staff Picks editor",
        }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Bio", name: "bio", widget: "markdown", required: false }
      - {
          label: "Twitter Handle",
          name: "twitter_handle",
          widget: "string",
          hint: "Without the @, eg. Catchpoint",
          required: false,
        }
  - name: "staff-picks" # Used in routes, e.g., /admin/collections/blog
    label: "Staff Picks" # Used in the UI
    folder: "src/staff-picks" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Picks"
        name: "picks"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Url", name: "url", widget: "string" }
          - label: "Type"
            name: "type"
            widget: "select"
            options: ["Video", "Article"]
          - { label: "Publish Date", name: "date", widget: "date" }
          - label: "Picked By"
            name: "picked_by"
            widget: "relation"
            collection: "authors"
            search_fields: ["name"]
            value_field: name
  - label: "Pages"
    name: "pages"
    files:
      - label: "Staff Picks"
        name: "staff-picks"
        file: "src/staff-picks.md"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "staff-picks",
            }
